---
version: 0.2
phases:
  pre_build:
      commands:
      - VERSION="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - find ./ -type f -exec sed -i -e "s/APP_VERSION/$VERSION/g" {} \;
  post_build:
    commands:
      - aws s3 sync . s3://$ORIGIN_BUCKET_NAME --exclude ".git/*"
